version: '3.8'

services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/java:21
    command: sleep infinity
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
